In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\anupr\OneDrive\Desktop\medical_disease\data\medical_disease_prediction_10000.csv")

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df.isnull().sum()

Age                 0
Gender              0
BMI                 0
BloodPressure       0
GlucoseLevel        0
Cholesterol         0
HeartRate           0
Smoking             0
Alcohol             0
PhysicalActivity    0
FamilyHistory       0
Disease             0
dtype: int64

In [5]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [6]:
df.Gender.unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [7]:
gender_dict={'Male':0,'Female':1}
df["Gender"]=df["Gender"].map(gender_dict)

In [11]:
yesno_dict={'No':0,'Yes':1}
df["Smoking"]=df["Smoking"].map(yesno_dict)
df["Alcohol"]= df["Alcohol"].map(yesno_dict)
df["FamilyHistory"]=df["FamilyHistory"].map(yesno_dict)

In [12]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,0,17.5,102,177,161,88,0,0,Medium,0,Healthy
1,69,0,31.1,118,256,147,92,0,0,High,1,Pre-Diabetes
2,61,1,31.3,114,206,193,74,1,0,Medium,0,Healthy
3,47,1,23.9,105,162,253,68,0,0,Low,0,Healthy
4,47,0,28.3,148,121,280,84,0,1,High,0,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,0,27.1,177,183,268,59,0,0,High,0,Hypertension
9996,84,0,29.2,142,215,145,77,0,1,High,1,Hypertension
9997,41,0,22.8,177,265,133,71,0,0,Medium,1,Hypertension
9998,55,0,29.0,126,241,298,57,0,0,Medium,1,Pre-Diabetes
9999,59,0,32.2,151,162,225,93,0,0,High,1,Pre-Diabetes

In [13]:
df.PhysicalActivity.unique()

<StringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

In [14]:
df.Disease.unique()

<StringArray>
['Healthy', 'Pre-Diabetes', 'Hypertension', 'Heart Disease', 'Diabetes']
Length: 5, dtype: str

In [15]:
PA_dict={'Medium':1, 'High':2, 'Low':0}
df["PhysicalActivity"]=df["PhysicalActivity"].map(PA_dict)

In [16]:
di_dict= {'Healthy':0, 'Pre-Diabetes':1, 'Hypertension':2, 'Heart Disease':3, 'Diabetes':4}

df["Disease"]=df["Disease"].map(di_dict)

In [17]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,0,17.5,102,177,161,88,0,0,1,0,0
1,69,0,31.1,118,256,147,92,0,0,2,1,1
2,61,1,31.3,114,206,193,74,1,0,1,0,0
3,47,1,23.9,105,162,253,68,0,0,0,0,0
4,47,0,28.3,148,121,280,84,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,0,27.1,177,183,268,59,0,0,2,0,2
9996,84,0,29.2,142,215,145,77,0,1,2,1,2
9997,41,0,22.8,177,265,133,71,0,0,1,1,2
9998,55,0,29.0,126,241,298,57,0,0,1,1,1
9999,59,0,32.2,151,162,225,93,0,0,2,1,1

In [18]:
df.to_csv("CleanedData.csv")